// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABFLjykFbjUISt6b7pcUEoPASVH8dyBF0',
    appId: '1:109147863197:web:80f580b557176d7aebbc74',
    messagingSenderId: '109147863197',
    projectId: 'dompetdigital-5c8b8',
    authDomain: 'dompetdigital-5c8b8.firebaseapp.com',
    storageBucket: 'dompetdigital-5c8b8.firebasestorage.app',
    measurementId: 'G-JHHE1W2JM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDjrMXxDUirOTapHKjCZuQR68J-RZfRqU',
    appId: '1:109147863197:android:7d6d13f65601d4ccebbc74',
    messagingSenderId: '109147863197',
    projectId: 'dompetdigital-5c8b8',
    storageBucket: 'dompetdigital-5c8b8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABFLjykFbjUISt6b7pcUEoPASVH8dyBF0',
    appId: '1:109147863197:web:bff483816c194a3cebbc74',
    messagingSenderId: '109147863197',
    projectId: 'dompetdigital-5c8b8',
    authDomain: 'dompetdigital-5c8b8.firebaseapp.com',
    storageBucket: 'dompetdigital-5c8b8.firebasestorage.app',
    measurementId: 'G-M8NH20TBBK',
  );
}
